general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 1200
}

animations {
    enabled = true
}

background {
    monitor =
    #path = screenshot
    path = ~/.config/hypr/bg1.jpg
    color = rgba(17, 17, 17, 1.0)

    blur_passes = 2
    contrast = 0.6916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.01
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(216, 222, 233, .75)
    font_size = 40
    font_family = SF Pro Display Bold
    position = 26, -50
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(LC_TIME=en_US.UTF-8 date +"%A, %B %d")"
    color = rgba(216, 222, 233, .75)
    font_size = 19
    font_family = SF Pro Display Bold
    position = 26, -20
    halign = left
    valign = top
}

input-field {
    monitor =
    size = 13%, 3.5%
    outline_thickness = 1

    dots_size = 0.15

    font_family = SF Pro Display Bold

    inner_color = rgba(216, 222, 233, .75)
    outer_color = rgba(216, 222, 233, .75)
    check_color = rgba(33ccffee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(44, 44, 44)
    fade_on_empty = false
    rounding = 8

    placeholder_text = Password
    fail_text = Wrong password!

    position = 0, -20
    halign = center
    valign = center
}
