$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$screenshotClipboard = grim - | wl-copy
$screenshotFile = grim
$screenshotPartial = grim -g "$(slurp)" - | wl-copy
$screenrecordStart = gpu-screen-recorder -w screen -f 60 -a default_output -o ~/Videos/rec_$(date +%d%m%H%M%S).mp4
$screenrecordStop = killall -s SIGINT gpu-screen-recorder | notify-send "OK" "Recording stopped..."

source = ~/.config/hypr/hyprland/binds.conf
source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/permissions.conf
source = ~/.config/hypr/hyprland/windowrules.conf
source = ~/.config/hypr/hyprland/visuals.conf
source = ~/.config/hypr/hyprland/input.conf
source = ~/.config/hypr/hyprland/force-darktheme.conf

