input {
    kb_layout = us,us,ua,ru
    kb_variant = # dvorak
    kb_model =
    kb_options = grp:win_space_toggle #grp:caps_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

