source = ~/.config/hypr/mocha.conf

monitor= HDMI-A-1, preferred, auto, 1.0
monitor= eDP-1, preferred, auto, 1.6
monitor= , preferred, auto, auto

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_AUTO_SCREEN_SCALE_FACTOR, 0

general {
    gaps_in = 0 # 4
    gaps_out = 0 # 8

    border_size = 1 

    col.active_border = rgb(005577)
    col.inactive_border = rgb(444444)

    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

cursor {
    inactive_timeout = 1
}

decoration {
    rounding = 0
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = false
        size = 4
        passes = 2

        vibrancy = 0.1696
    }
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

