source = ~/.config/hypr/mocha.conf

monitor= HDMI-A-1, preferred, auto, 1.0
monitor= eDP-1, preferred, auto, 1.4
monitor= , preferred, auto, auto

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_AUTO_SCREEN_SCALE_FACTOR, 0

general {
    gaps_in = 4
    gaps_out = 8

    border_size = 2

    col.active_border = $peach
    col.inactive_border = $rosewater

    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

cursor {
    inactive_timeout = 1
}

decoration {
    rounding = 4
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 0.97

    shadow {
        enabled = false
    }

    blur {
        enabled = true
        size = 4
        passes = 2

        vibrancy = 0.1696
    }
}

dwindle {
    pseudotile = true 
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

