monitor=,preferred,auto,auto

general {
    gaps_in = 4
    gaps_out = 8

    border_size = 1

    col.active_border = rgba(ffffffff) 
    col.inactive_border = rgba(ffffffaa)

    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

cursor {
    inactive_timeout = 1
}

decoration {
    rounding = 0
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = true
        size = 4
        passes = 2

        vibrancy = 0.1696
    }
}

dwindle {
    pseudotile = true 
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

