#!/usr/bin/env bash

# todo: install speakersafetyd on asahi linux only
arch_packages=(\
    wl-clipboard zsh ttf-cascadia-mono-nerd \
    pipewire pipewire-alsa pipewire-pulse \
    power-profiles-daemon \
    adw-gtk-theme qt5ct qt6ct kvantum kvantum breeze-icons \

    # nvim
    tree-sitter-cli fd lua-language-server rust-analyzer
)

if command -v pacman >/dev/null; then
    echo "Arch Linux detected!"
    sudo pacman -Sy --needed "${arch_packages[@]}"
else
    echo "Unsupported distribution."
    exit 1
fi
