#!/usr/bin/env bash

if [[ $1 == "" ]]; then
    echo "Usage: ssh-keygen <email>"
    exit
fi

ssh-keygen -t ed25519 -C "$1"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
cat ~/.ssh/id_ed25519.pub
