#!/usr/bin/env bash

QT5="$HOME/.config/qt5ct/qt5ct.conf"
QT6="$HOME/.config/qt6ct/qt6ct.conf"

CURRENT_MODE=$(gsettings get org.gnome.desktop.interface color-scheme)

TERM_LIGHT_THEME="$(cat "$HOME/.config/alacritty/light.toml")"
TERM_DARK_THEME="$(cat "$HOME/.config/alacritty/dark.toml")"

if [ "$CURRENT_MODE" = "'prefer-dark'" ]; then
    echo 'light'
    gsettings set org.gnome.desktop.interface color-scheme "default"
    gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"

    sed -i 's|color_scheme_path=.*|color_scheme_path=/usr/share/qt5ct/colors/airy.conf|' "$QT5"
    sed -i 's|icon_theme=.*|icon_theme=breeze|' "$QT5"

    sed -i 's|color_scheme_path=.*|color_scheme_path=/usr/share/qt6ct/colors/airy.conf|' "$QT6"
    sed -i 's|icon_theme=.*|icon_theme=breeze|' "$QT6"

    alacritty msg config "$TERM_LIGHT_THEME"
else
    echo 'dark'
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
    gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"

    sed -i 's|color_scheme_path=.*|color_scheme_path=/usr/share/qt5ct/colors/darker.conf|' "$QT5"
    sed -i 's|icon_theme=.*|icon_theme=breeze-dark|' "$QT5"

    sed -i 's|color_scheme_path=.*|color_scheme_path=/usr/share/qt6ct/colors/darker.conf|' "$QT6"
    sed -i 's|icon_theme=.*|icon_theme=breeze-dark|' "$QT6"

    alacritty msg config "$TERM_DARK_THEME"
fi
