[general]
live_config_reload =  true
ipc_socket = true
import = [
    "~/.config/alacritty/dark.theme"
]

[window]
opacity = 0.96
blur = true

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }

[terminal]
shell = { program = "/bin/zsh" }
